In [203]:
import pandas as pd
from sklearn.decomposition import PCA

In [204]:
pca = PCA(n_components=0.98)

In [205]:
df_train = pd.read_csv('../Standardization/X_Train.csv')
df_test = pd.read_csv('../Standardization/X_Test.csv')

In [206]:
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-1.668553,-1.297257,0.971568,0.475563,0.761505,0.150822,-0.050301,0.658133,0.410332,-1.445036,...,-0.236296,0.517192,2.258106,2.153228,2.069651,1.466814,1.124492,1.122890,0.673239,1.041177
1,0.375962,-0.737954,-0.477299,1.796089,-0.880277,1.412751,-1.445570,1.103039,-0.563930,-1.153701,...,0.266311,0.597057,2.200927,2.615331,2.393242,2.462550,1.393881,1.832941,-0.583629,1.048322
2,-0.504520,-0.738341,-0.142185,1.384818,-0.117215,0.696192,-1.107991,1.147937,-0.185496,-0.196293,...,0.572048,0.831532,1.552937,1.073207,1.010550,1.348373,1.036660,1.640945,-0.400277,0.546960
3,0.368656,-0.550225,-0.414720,1.556328,-0.168473,1.235944,-1.194858,1.053096,-0.086577,-0.503798,...,0.389020,0.112335,1.276183,0.987278,1.000080,1.609324,0.830929,1.712292,-0.539691,0.843585
4,0.117317,0.082294,-0.799503,1.769532,-0.636372,1.052015,-1.575918,1.049943,-0.266061,-0.457494,...,1.351606,1.256882,1.811191,1.082727,0.694154,1.542801,0.726971,1.976923,-0.291456,0.803440

In [207]:
df_test.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,0.458850,-0.829371,-0.291432,1.374824,-0.715761,1.972980,-1.553072,0.503142,-2.341967,0.459910,...,0.697867,0.456045,0.990348,0.868418,0.655190,2.358937,0.572945,2.636054,0.856872,2.149753
1,-1.995583,-1.401461,1.323905,-2.622218,1.294457,-1.584414,1.139461,-1.117208,0.467971,-0.975320,...,-1.809591,-1.493165,-1.016568,-1.148028,-0.652023,-1.603952,-0.829528,-1.312239,0.278116,-0.855793
2,-2.714360,-1.483719,1.591406,-2.811384,1.078821,-1.367445,1.241061,-1.394285,0.961058,-0.853943,...,-1.884634,-1.552143,-1.091953,-1.270365,-0.956788,-1.686785,-0.725971,-1.606569,0.060826,-1.529826
3,0.051808,-1.622699,-0.015429,-0.222292,-0.794603,0.846228,-1.251717,1.121852,-1.627941,-0.519179,...,0.473457,-0.282225,-0.742769,-1.097783,-1.362255,-0.989488,-1.362835,-0.043227,-1.979163,-2.352361
4,1.185420,-0.782067,-0.834607,0.709045,-1.616020,1.421932,-2.034431,1.366501,-2.230820,0.152144,...,1.256098,1.152314,0.412534,0.163235,-1.281383,-0.826437,-1.537339,0.396087,-1.428929,-0.979686

In [208]:

df_train_pca = pca.fit_transform(df_train)
df_train = pd.DataFrame(df_train_pca)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3.228257,-3.895754,0.439289,-3.119140,-0.124297,3.296204,-1.306570,0.092134,-0.263962,1.072149,...,-0.540267,-0.506481,0.595889,0.038230,0.827951,0.087367,0.205539,0.225651,-0.544702,0.189591
1,5.784951,0.141297,1.504760,-2.898648,0.587837,3.875052,-1.305656,0.948700,-0.616534,0.731709,...,-0.316920,-0.609942,-0.282016,0.122035,0.423062,0.337513,-0.363146,0.081686,-0.282699,0.172636
2,3.184874,-0.431706,1.522862,-3.354339,1.063571,2.514552,-1.248302,0.385098,-0.781940,0.903872,...,0.549407,-0.807953,-0.443648,-0.097953,0.495333,0.203449,-0.397007,-0.111205,-0.847389,0.382253
3,3.468742,0.123525,2.065360,-2.900889,1.224283,2.459811,-1.371042,0.523343,-1.093648,1.293194,...,0.500108,-0.761388,-0.347198,-0.071910,0.191739,0.155024,-0.156890,-0.280901,-0.509331,0.138586
4,4.231784,1.179424,1.144901,-3.371371,1.649588,2.155622,-1.018549,1.335554,-1.745297,1.751915,...,0.438574,-0.556538,-0.542271,-0.082422,0.851750,-0.155700,-0.476923,-0.048685,-0.592706,0.275088

In [209]:
df_train.to_csv('X_Feature_Train.csv', index=0)

In [210]:
df_test_pca = pca.transform(df_test)
df_test = pd.DataFrame(df_test_pca)
df_test.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,5.360016,1.268690,2.161381,-1.588061,2.963310,0.308052,-1.629248,-0.848800,-0.027544,-0.260601,...,0.188941,0.464906,0.387479,0.268745,0.499823,0.064484,-0.148116,-0.307058,-0.597952,-0.078127
1,-2.725435,-3.464225,-2.482208,3.106617,0.018250,-0.671377,0.415723,-0.166357,3.024277,2.966274,...,-1.019673,0.910761,-0.057833,-0.719058,-0.956758,-0.280459,-0.193249,0.605115,0.192169,0.043191
2,-3.385572,-4.305683,-1.884385,2.607798,-0.387973,-0.487946,1.044357,0.167195,3.297239,2.784505,...,-0.557021,1.398033,-0.321252,-0.636290,-0.706302,-0.523679,-0.678233,0.358964,0.115146,0.139449
3,-2.625699,3.198176,1.704338,-1.433637,0.169089,0.639229,1.363356,-1.155707,1.071514,0.994695,...,-0.334371,0.448592,-1.340038,0.101845,-0.534111,-0.286398,-0.204031,0.100462,-0.227164,-0.539955
4,0.262678,5.981059,0.444055,-1.147388,0.955649,-0.029556,0.586886,-0.332088,1.084343,-0.158934,...,-0.574167,0.958759,0.446603,1.209583,-0.242496,-0.111684,-0.203795,-0.099174,-0.324050,0.205519

In [211]:
df_test.to_csv('X_Feature_Test.csv', index=0)